### ISSUE TITLE
Add more request endpoint

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/bridge-contracts#22]
### Describe the problem you discovered

Currently the bridge request informations to ethereum using endpoint API, but we use only one endpoint.
This could be a problem if the endpoint is not reacheable anymore.

### Describe the solution you'd like

We should request informations using multiple endpoints

**Comment by bchamagne** [comment]
Current implementation of HTTP module function `request_many` is a do-all-or-raise. 
This is useful to write the contract in "happy path": the developers do not have to handle the errors themselves. 
But this is limiting for some scenarios like this issue where the developers actually need to handle the errors themselves.

Here's a few suggested solutions: 

1. Remove the do-all-or-raise and let all the developers handle the errors 
2. Create a new function such as `request_many_raw` where the result is the same length and order but contains both successes and errors
3. Create a new function such as `request_some` where the result is only the successes

**Comment by Neylix** [comment]
4. Add a new optionnal argument `throw_on_error`  to the functions (request / request_many) default would be true to keep the current behavior, if false the request would return specific errors (as firstly described in the AEIP)
